name: calculator
description: "A flutter calculator."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  icons_launcher: ^3.0.3
  math_expressions: ^3.1.0
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_driver:
    sdk: flutter
  test: any
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  
icons_launcher:
  image_path: "assets/icon/icon.png"
  platforms:
    linux:
      enable: true

assets:
  - assets/icon/icon.png
